config/routes.rb
Rails.application.routes.draw do
  resources :employee_educations
  resources :employee_skills
  resources :skills
  resources :educations
  resources :evaluations
  resources :positions
  resources :promotions
  devise_for :employees
  resources :employees do
    post 'edit_indy', :on => :collection
    put 'update_indy', :on => :collection
  end
  get "home/show"

  

    root 'home#index'

end

app/models/position.rb
class Position < ActiveRecord::Base
	ROLE_TYPES = ["Team Leader", "Supervisor", "Manager", "Human Resources"]
	LEVEL_TYPES = ["A3", "B1", "B2", "B3", "C1", "C2", "C3", "D", "E"]
	has_many :employees
	
	def pos_name
		name + ' ' + level
	end
	def position_rollup
		name + ' ' + level + ' ' + role
	end
	
	def pos_role
		name
	end
	
	def emp_role
		role.titleize
	end
	
	def self.search search_term
  		where(['level LIKE ?', "%#{search_term}%"])
  	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @ex = Position.where(level: "E").order(name: :asc)
    @dir = Position.where(level: "D").order(name: :asc)
	#mgr
    @c3 = Position.where(level: "C3").order(name: :asc)
    @b3 = Position.where(level: "B3").order(name: :asc)
	#sup
    @c2 = Position.where(level: "C2").order(name: :asc)
    @b2 = Position.where(level: "B2").order(name: :asc)
    @c1 = Position.where(level: "C1").order(name: :asc)
    @b1 = Position.where(level: "C1").order(name: :asc)
	#tl
    @tl = Position.where(level: "A3").order(name: :asc)
    @position = Position.new
    respond_with(@position)
  end

  def show
    respond_with(@position)
  end

  def new
    @position = Position.new
    respond_with(@position)
  end

  def edit
  end

  def create
    @position = Position.new(position_params)
    @position.save
    redirect_to positions_url
  end

  def update
    @position.update(position_params)
    respond_with(@position)
  end

  def destroy
    @position.destroy
    respond_with(@position)
  end

  private
    def set_position
      @position = Position.find(params[:id])
    end

    def position_params
      params.require(:position).permit(:name, :level, :role)
    end
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
    <%= f.text_field :name, :placeholder => "position name" %>
    <%= f.select :level, Position::LEVEL_TYPES, :prompt => "Grade" %>
    <%= f.select :role, Position::ROLE_TYPES, :prompt => "Role" %>
    <%= f.submit "Add Position" %>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render 'form' %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<div id="supportnavi">
	<ul>
		<li><%= link_to 'my dashboard', root_path %></li>
		<li><%= link_to 'add educations', educations_path %></li>
		<li><%= link_to 'add skill-sets', skills_path %></li>
		<li class="current"><%= link_to 'add positions', positions_path %></li>
	</ul>
</div>
<div id="positions">
	<div class="topleft">
	<h2>Executives</h2>
		<% @ex.each do |e| %>
			<p><%= e.name.upcase %></p>
		<% end %>
  	</div>  
	<div class="topmid">
	<h2>Directors</h2>
		<% @dir.each do |d| %>
			<p><%= d.name.upcase %></p>
		<% end %>
  	</div>  
	<div class="topright">
	<h2>Managers</h2>
		<% @c3.each do |c3| %>
			<p><%= c3.name.upcase %></p>
		<% end %>
		<% @b3.each do |b3| %>
			<p><%= b3.name.upcase %></p>
		<% end %>
  	</div>  
	<div class="botleft">
	<h2>Supervisors</h2>
		<% @c2.each do |c2| %>
			<p><%= c2.name.upcase %></p>
		<% end %>
		<% @b2.each do |b2| %>
			<p><%= b2.name.upcase %></p>
		<% end %>
		<% @c1.each do |c2| %>
			<p><%= c2.name.upcase %></p>
		<% end %>
		<% @b1.each do |b2| %>
			<p><%= b2.name.upcase %></p>
		<% end %>
  	</div>  
	<div class="botright">
	<h2>Team Leaders</h2>
		<% @tl.each do |t| %>
			<p><%= t.name.upcase %></p>
		<% end %>
  	</div> 
<%= render 'form' %>

</div>    

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render 'form' %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @position.name %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>