config/routes.rb
Rails.application.routes.draw do
  resources :employee_educations
  resources :employee_skills
  resources :skills
  resources :educations
  resources :evaluations
  resources :positions
  resources :promotions
  devise_for :employees
  resources :employees do
    post 'edit_indy', :on => :collection
    put 'update_indy', :on => :collection
  end
  get "home/show"

  

    root 'home#index'

end

app/models/education.rb
class Education < ActiveRecord::Base
	ED_TYPES = ["diploma/GED","bachelor's", "master's"]

	has_many :employee_educations
	
	def conName
		concentration.humanize
	end
	def education_name
		degree + ' ' + concentration
	end
	def edname
		degree + ': ' + concentration
	end
	def deg
		degree
	end

	def self.search search_term
  		where(['degree LIKE ?', "%#{search_term}%"])
  	end

end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @educations = Education.all
    @ged = Education.where(degree: "diploma/GED")
    @bachelor = Education.where(degree: "bachelor's").order(concentration: :asc)
    @master = Education.where(degree: "master's").order(concentration: :asc)
    @education = Education.new
    respond_with(@education)
  end

  def show
    respond_with(@education)
  end

  def new
    @education = Education.new
    respond_with(@education)
  end

  def edit
  end

  def create
    @education = Education.new(education_params)
    @education.save
    redirect_to educations_url
  end

  def update
    @education.update(education_params)
    respond_with(@education)
  end

  def destroy
    @education.destroy
    respond_with(@education)
  end

  private
    def set_education
      @education = Education.find(params[:id])
    end

    def education_params
      params.require(:education).permit(:degree, :concentration)
    end
end

app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>  
    <%= f.select :degree, Education::ED_TYPES %>
    <%= f.text_field :concentration, :placeholder => "concentration" %>  
    <%= f.submit "Add Education" %>
<% end %>

app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<div id="supportnavi">
	<ul>
		<li><%= link_to 'my dashboard', root_path %></li>
		<li class="current"><%= link_to 'add educations', educations_path %></li>
		<li><%= link_to 'add skill-sets', skills_path %></li>
		<li><%= link_to 'add positions', positions_path %></li>
	</ul>
</div>

<div id="ged">
	<h1>High School or GED</h1>
	<% @ged.each do |ged| %>
		<p><%= ged.conName %></p>
	<% end %>
</div>

<div id="bachelor">
	<h1>Bachelor's</h1>
	<% @bachelor.each do |bachelor| %>
		<p><%= bachelor.conName %></p>
	<% end %>
</div>

<div id="master">
	<h1>Master's</h1>
	<% @master.each do |master| %>
		<p><%= master.conName %></p>
	<% end %>
</div>

<%= render 'form' %>

app/views/educations/new.html.erb
<h1>New education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Degree:</strong>
  <%= @education.degree %>
</p>

<p>
  <strong>Concentration:</strong>
  <%= @education.concentration %>
</p>


<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>