config/routes.rb
Rails.application.routes.draw do
  resources :employee_educations
  resources :employee_skills
  resources :skills
  resources :educations
  resources :evaluations
  resources :positions
  resources :promotions
  devise_for :employees
  resources :employees do
    post 'edit_indy', :on => :collection
    put 'update_indy', :on => :collection
  end
  get "home/show"

  

    root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HR Promotion DSS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if employee_signed_in? && current_employee.position_id.present? %>
		<div id="hr">
			<div class= "navi">
				<div class= "weak">
					<ul>
						<% if current_employee.emp_role == "Human Resources" %>
							<li><%= link_to 'PROMOTION DSS', promotions_path %></li>
							<li><%= link_to 'EVALUATIONS', evaluations_path %></li>
							<li><%= link_to 'EDUCATIONS', employee_educations_path %></li>	
							<li><%= link_to 'SKILLS', employee_skills_path %></li>
							<li><%= link_to 'POSITIONS', employees_path %></li>
						<% else %>
						<% end %>
					</ul>
				</div>
				<div class= "strong">
				<% if employee_signed_in? %>
					<p class="userside">Signed in as <%= current_employee.fname.humanize %> |
					<%= link_to 'logout', destroy_employee_session_path, :method => :delete %> </p>
				<% else %>
				<% end %>
				</div>
			</div>
	<% else %>
	<% end %>
	<%= yield %>
</div>
</body>
</html>